Actions:
  - Name: applicationinsights:CreateApplication
  - Name: applicationinsights:CreateComponent
  - Name: applicationinsights:DeleteApplication
  - Name: applicationinsights:DeleteComponent
  - Name: applicationinsights:DescribeApplication
  - Name: applicationinsights:DescribeComponent
  - Name: applicationinsights:DescribeComponentConfiguration
  - Name: applicationinsights:DescribeComponentConfigurationRecommendation
  - Name: applicationinsights:DescribeObservation
  - Name: applicationinsights:DescribeProblem
  - Name: applicationinsights:DescribeProblemObservations
  - Name: applicationinsights:ListApplications
  - Name: applicationinsights:ListComponents
  - Name: applicationinsights:ListProblems
  - Name: applicationinsights:UpdateApplication
  - Name: applicationinsights:UpdateComponent
  - Name: applicationinsights:UpdateComponentConfiguration
