Actions:
  - Name: config:BatchGetAggregateResourceConfig
  - Name: config:BatchGetResourceConfig
  - Name: config:DeleteAggregationAuthorization
  - Name: config:DeleteConfigRule
  - Name: config:DeleteConfigurationAggregator
  - Name: config:DeleteConfigurationRecorder
  - Name: config:DeleteDeliveryChannel
  - Name: config:DeleteEvaluationResults
  - Name: config:DeletePendingAggregationRequest
  - Name: config:DeleteRemediationConfiguration
  - Name: config:DeleteRetentionConfiguration
  - Name: config:DeliverConfigSnapshot
  - Name: config:DescribeAggregateComplianceByConfigRules
  - Name: config:DescribeAggregationAuthorizations
  - Name: config:DescribeComplianceByConfigRule
  - Name: config:DescribeComplianceByResource
  - Name: config:DescribeConfigRuleEvaluationStatus
  - Name: config:DescribeConfigRules
  - Name: config:DescribeConfigurationAggregatorSourcesStatus
  - Name: config:DescribeConfigurationAggregators
  - Name: config:DescribeConfigurationRecorderStatus
  - Name: config:DescribeConfigurationRecorders
  - Name: config:DescribeDeliveryChannelStatus
  - Name: config:DescribeDeliveryChannels
  - Name: config:DescribePendingAggregationRequests
  - Name: config:DescribeRemediationConfigurations
  - Name: config:DescribeRemediationExecutionStatus
  - Name: config:DescribeRetentionConfigurations
  - Name: config:GetAggregateComplianceDetailsByConfigRule
  - Name: config:GetAggregateConfigRuleComplianceSummary
  - Name: config:GetAggregateDiscoveredResourceCounts
  - Name: config:GetAggregateResourceConfig
  - Name: config:GetComplianceDetailsByConfigRule
  - Name: config:GetComplianceDetailsByResource
  - Name: config:GetComplianceSummaryByConfigRule
  - Name: config:GetComplianceSummaryByResourceType
  - Name: config:GetDiscoveredResourceCounts
  - Name: config:GetResourceConfigHistory
  - Name: config:ListAggregateDiscoveredResources
  - Name: config:ListDiscoveredResources
  - Name: config:ListTagsForResource
  - Name: config:PutAggregationAuthorization
  - Name: config:PutConfigRule
  - Name: config:PutConfigurationAggregator
  - Name: config:PutConfigurationRecorder
  - Name: config:PutDeliveryChannel
  - Name: config:PutEvaluations
  - Name: config:PutRemediationConfigurations
  - Name: config:PutRetentionConfiguration
  - Name: config:SelectResourceConfig
  - Name: config:StartConfigRulesEvaluation
  - Name: config:StartConfigurationRecorder
  - Name: config:StartRemediationExecution
  - Name: config:StopConfigurationRecorder
  - Name: config:TagResource
  - Name: config:UntagResource

  # actions with no corresponding API
  - Name: config:GetResources
  - Name: config:GetTagKeys

  # APIs without an IAM action
  - Name: config:DeleteConformancePack
  - Name: config:DeleteOrganizationConfigRule
  - Name: config:DeleteOrganizationConformancePack
  - Name: config:DeleteRemediationExceptions
  - Name: config:DescribeConformancePackCompliance
  - Name: config:DescribeConformancePackStatus
  - Name: config:DescribeConformancePacks
  - Name: config:DescribeOrganizationConfigRuleStatuses
  - Name: config:DescribeOrganizationConfigRules
  - Name: config:DescribeOrganizationConformancePackStatuses
  - Name: config:DescribeOrganizationConformancePacks
  - Name: config:DescribeRemediationExceptions
  - Name: config:GetConformancePackComplianceDetails
  - Name: config:GetConformancePackComplianceSummary
  - Name: config:GetOrganizationConfigRuleDetailedStatus
  - Name: config:GetOrganizationConformancePackDetailedStatus
  - Name: config:PutConformancePack
  - Name: config:PutOrganizationConfigRule
  - Name: config:PutOrganizationConformancePack
  - Name: config:PutRemediationExceptions
