name: Check upstream for new actions

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  upstream:
    name: Upstream
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run it
        run: go run main.go

      - name: Commit files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add .
          git commit -m "New actions" -a || exit 0

          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${remote_repo}" HEAD:master
